# Site Metadata
site_name: "Documentation"
site_url: "https://yourdomain.com/docs"
site_author: "Your Name"
site_description: "A custom, documentation site built with MkDocs and Material for MkDocs."

# Navigation
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Usage:
      - Basic Usage: usage/basic.md
      - Advanced Techniques: usage/advanced.md
  - API Reference: api/reference.md
  - Tutorials:
      - Tutorial One: tutorials/tutorial-one.md
      - Tutorial Two: tutorials/tutorial-two.md
  - About: about.md

# Theme Configuration (using Material for MkDocs)
theme:
  name: material
  language: en
  favicon: "images/favicon.ico"
  logo: "images/logo.png"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
    - toc.integrate  # Integrate table of contents in page content

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      locale: en
      fallback_to_build_date: false
  - minify:
      minify_html: true

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - attr_list

# Extra Variables and Assets
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/yourusername/yourrepo"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/yourprofile"
    - icon: fontawesome/brands/linkedin
  analytics:
    provider: google
    tracking_id: UA-XXXXXXX-X
  custom_css: "css/custom.css"
  custom_js: "js/custom.js"

extra_css:
  - "css/custom.css"
extra_javascript:
  - "js/custom.js"

# Repository Settings
repo_url: "https://github.com/yourusername/yourrepo"
repo_name: "GitHub"
