name: Run Tests and Generate Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.2.2'

      - name: Install dependencies via Poetry
        run: poetry install --no-interaction --no-ansi

      - name: Run Tests with HTML Report
        run: poetry run pytest --html=report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report.html
